### PR TITLE
Fix: Windows build failing due to invalid path in Flutter v3.16.0 and v3.15.0-pre 

### LINKED ISSUE #145: 如何配置Release路径？Directory listing failed, path = 'build/windows/runner/Release\*'
如何配置Release路径？打包后如图多了一个x64层级，导致Directory listing failed, path = 'build/windows/runner/Release\*'
image

### PR DESCRIPTION
**Pull request by KRTirtho**
Fixes #145

### CODE REVIEW

**Comment by KRTirtho** [comment]
@lijy91 important fix. Please review asap 😄 
Will require a new release

Thanks for the library again ❤️

**Comment by karniv00l** [comment]
Thanks @KRTirtho!

**Comment by lijy91** [comment]
LGTM

**Comment by lijy91** [comment]
I have improved this fix, please take a look https://github.com/leanflutter/flutter_distributor/commit/d69125d7c9f3c46c04ee55fcd3d501e123e81de6

**Comment by KRTirtho** [comment]
Yeah, that's even better. Now, it should be future-proof for a while 😅

**Pull request merged**
