### PR TITLE
chore: bump http and dio deps

### PR DESCRIPTION
**Pull request by lexxxel**

### CODE REVIEW

**Comment by lijy91** [comment]
LGTM

**Comment by lijy91** [comment]
I have revert this PR, and in order to maintain a minimum compatibility of 2.16, I cannot upgrade Google API to 11.4.0

**Comment by lexxxel** [comment]
> I have revert this PR, and in order to maintain a minimum compatibility of 2.16, I cannot upgrade Google API to 11.4.0

What do you mean with 2.16? Do you mean dart 2.16?
I ask, because this makes this package incompatible with other packages, e.g. pocketbase.

Typically one could solve this by creating a new major release and still backport/release patches to the older major version, but of course that would increase you maintenance burden.
However, otherwise one would have to fork your project to get said compatibility with other packages.
What is your opinion on that?

**Comment by lijy91** [comment]
Aren't you installing it globally? It shouldn't affect your own project dependencies.

**Comment by lexxxel** [comment]
> Aren't you installing it globally? It shouldn't affect your own project dependencies.

No I did not. Thank you for the inside. That will fix my dependency issue.

**Pull request merged**
