### PR TITLE
[FEAT] Add support for Pacman (Arch Linux)

### LINKED ISSUE #175: Support .pacman format
Arch users are only able to install apps using .pacman format and there are a lot of arch users. I think if flutter_distributor supports .pacman format then it would cater to all the top linux formats.

### PR DESCRIPTION
**Pull request by prateekmedia**
The output pacman package is not tested thoroughly, request people to test and give feedback.

I have followed the approach from [this article](https://gist.github.com/Earnestly/bebad057f40a662b5cc3), to test this you basically need to have bsdtar and xz.

Use the following command to test this PR:
```
dart pub global activate --source git https://github.com/prateekmedia/flutter_distributor --git-ref pacman --git-path packages/flutter_distributor
```

Closes #175

### CODE REVIEW

**Comment by lijy91** [comment]
LGTM

**Comment by lijy91** [comment]
@prateekmedia Can you provide some documentation for `pacman` maker?

**Comment by prateekmedia** [comment]
@lijy91 Where should I place the documentation?

**Comment by lijy91** [comment]
https://github.com/leanflutter/flutter_distributor/tree/main/website/src/content/docs/makers

**Comment by kjxbyz** [comment]
`flutter_distributor` adds support for `pacman`, but documentation is missing.

**Comment by OldSaltFish** [comment]
> @lijy91 Where should I place the documentation?

> https://github.com/leanflutter/flutter_distributor/tree/main/website/src/content/docs/makers

Documentation related to pacman configuration is needed.There are no relevant explanations provided on the webpage.

**Comment by FantixX** [comment]
waiting for docs as well

**Comment by labulakalia** [comment]
build package can noy install 
```
namcap -m  hello_world-1.0.0+1-profile-linux.pkg.tar.xz
ERROR: missing package name in /tmp/namcap.y0G6zPBu5U/hello_world-1.0.0+1-profile-linux.pkg.tar
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.13/site-packages/namcap.py", line 253, in <module>
    process_realpackage(package, active_modules)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/namcap.py", line 95, in process_realpackage
    rule.analyze(pkginfo, pkgtar)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/Namcap/rules/anyelf.py", line 19, in analyze
    if any(re.search(s, pkginfo["name"]) for s in supress_name):
       ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/Namcap/rules/anyelf.py", line 19, in <genexpr>
    if any(re.search(s, pkginfo["name"]) for s in supress_name):
                        ~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```
```
sudo pacman -U hello_world-1.0.0+1-profile-linux.pkg.tar.xz
正在加载软件包...
错误：hello_world-1.0.0+1-profile-linux.pkg.tar.xz 中缺少软件包名字
错误：'hello_world-1.0.0+1-profile-linux.pkg.tar.xz': 无效或已损坏的软件包
```

**Pull request merged**
