### PR TITLE
Feat/macos builder support flavor

### LINKED ISSUE #133: How to change path build macos ???
from "outputDirectory": "build/macos/Build/Products/Release" to build/macos/Build/Products/Release-uat/
Please!!!

`{
  "config": {
    "mode": "release",
    "flavor": "uat",
    "arguments": {
      "dart-define": {
        "APP_ENV": "dev"
      },
      "flavor": "uat",
      "target": "lib/main_uat.dart"
    }
  },
  "outputDirectory": "build/macos/Build/Products/Release",
  "duration": 457358,
  "outputFiles": []
}
Successfully built Directory: 'build/macos/Build/Products/Release' in 457s
PathNotFoundException: Directory listing failed, path = 'build/macos/Build/Products/Release/' (OS Error: No such file or directory, errno = 2)

RELEASE FAILED in 489s
PathNotFoundException: Directory listing failed, path = 'build/macos/Build/Products/Release/' (OS Error: No such file or directory, errno = 2)
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42:24)
#1      _Directory.listSync (dart:io/directory_impl.dart:233:5)
#2      AppPackageMakerZip.make (package:flutter_app_packager/src/makers/zip/app_package_maker_zip.dart:30:12)
#3      FlutterAppPackager.package (package:flutter_app_packager/src/flutter_app_packager.dart:40:18)
#4      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:182:51)
<asynchronous suspension>
#5      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:327:45)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
`

### PR DESCRIPTION
**Pull request by lijy91**

### CODE REVIEW

**Comment by shubhamsinghmutualmobile** [comment]
@lijy91 Is there a way for me to test this new code? I am using this:
```sh
fvm dart pub global activate -sgit https://github.com/leanflutter/flutter_distributor.git --git-path packages/flutter_distributor/ --git-ref 0abe930d073c0d679038a00c09e4388e5e55ebd8 --overwrite
```
but getting the following error:
```
Because every version of flutter_distributor from git depends on flutter_app_builder ^0.4.4 which doesn't match any versions, flutter_distributor from git is forbidden.
So, because pub global activate depends on flutter_distributor from git, version solving failed.
```

**Comment by lijy91** [comment]
Try this
```
git clone git@github.com:leanflutter/flutter_distributor.git
cd flutter_distributor
melos bs
melos activate
```

**Comment by shubhamsinghmutualmobile** [comment]
> Try this
> 
> ```
> git clone git@github.com:leanflutter/flutter_distributor.git
> cd flutter_distributor
> gh pr checkout 196
> melos bs
> melos activate
> ```

Still doesn't seem to work for me :( Do you think I might be doing something wrong?

Screenshot 2024-06-16 at 6 04 18 AM

**Comment by lijy91** [comment]
Did you add flavor to build_args ?

**Comment by lijy91** [comment]
Can you try build the multiple_flavors example
```
cd examples/multiple_flavors 
./release.sh dmg-release
```

**Comment by shubhamsinghmutualmobile** [comment]
> Can you try build the multiple_flavors example
> 
> ```
> cd examples/multiple_flavors 
> ./release.sh dmg-release
> ```

I did try it out.. the example in your repository works perfectly fine 👍 but I'm not able to understand why it's not working inside my repository 🤔 I have added the `flavor` build argument but still it isn't detected 🤔 

Here's my `distribute_options.yaml` file, do you see anything missing here?

Screenshot 2024-06-16 at 6 35 31 AM

**Comment by lijy91** [comment]
Please provide a screenshot of your scheme configuration, And your build/macos/Build/Products directory.

image

image

**Comment by shubhamsinghmutualmobile** [comment]
I did not realise that the command `gh pr checkout 196` did not work for me. Hence, I was using the `main` branch to build the plugin 🤦 Apologies for that. I just verified that this PR is working fine on my project as well ✅

Screenshot 2024-06-16 at 7 20 08 AM

Although I see a new problem now i.e.
```
Error on line 10, column 16: Expected a key while parsing a block mapping.
   ╷
10 │     path: [DEV]Ember.app
   │                ^
   ╵
```
but I believe that's not a part of this discussion. We can discuss it in another issue.

For now, thank you for your quick support on this feature! 🙌

**Pull request merged**
